tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "ag"
brew "asdf"
brew "cocoapods"
brew "ctags"
brew "fasd"
brew "gh"
brew "mas"
brew "nodebrew"
# brew "pyenv"
brew "python"
# brew "rustup"
# brew "svn"
brew "the_silver_searcher"
# brew "tig"
brew "vim"
brew "zsh"
brew "wget"

# Apps
cask "1password"
cask "android-studio"
cask "blender"
cask "cocoapods" # M1 Macでcocoapodsを使うためにBrewでインストールする必要がある
cask "datagrip"
cask "deepl"
cask "discord"
cask "docker"
cask "dotnet-sdk"
# cask "dropbox"
cask "evernote"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "grammarly"
cask "intellij-idea"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
# cask "keepassxc"
# cask "kensington-trackball-works"
cask "macvim"
# cask "microsoft-office"
cask "microsoft-teams"
cask "miro"
cask "notion"
cask "rectangle"
cask "sf-symbols"
cask "sketch"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "temurin8"
cask "uhk-agent"
cask "visual-studio-code"
cask "zoom"

# App Store
# mas "Xcode", id: 497799835
mas "Horo", id: 1437226581
mas "Kindle", id: 405399194
mas "LINE", id: 539883307

# fonts
cask "font-hackgen"
cask "font-ricty-diminished"
cask "font-roboto"
