[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'patstockwell/vim-monokai-tasty'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
